# -*- coding: utf-8 -*-
"""hydblooms.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PiLrqN83yTklfBXohG0b5aEYCt2OdcMM
"""

import requests
import zipfile
import io
import pandas as pd

url = "https://training-ipt-b.gbif.org/archive.do?r=wwf-hat-survey-2024&v=1.0"

print("Downloading DwC-A archive...")
response = requests.get(url)
response.raise_for_status()

with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    print("Files in archive:", z.namelist())

    with z.open("occurrence.txt") as f:
        occurrences = pd.read_csv(f, sep="\t", low_memory=False)

    with z.open("event.txt") as f:
        events = pd.read_csv(f, sep="\t", low_memory=False)

print(f"Events     : {len(events)} records, {len(events.columns)} columns")
print(f"Occurrences: {len(occurrences)} records, {len(occurrences.columns)} columns")

# Merge occurrences with their parent event (join on eventID / id)
merged = occurrences.merge(
    events,
    left_on="id",
    right_on="id",
    how="left",
    suffixes=("_occurrence", "_event")
)
print(f"Merged     : {len(merged)} records, {len(merged.columns)} columns")

# Save individual files
events.to_csv("events.csv", index=False)
print("Saved → events.csv")

occurrences.to_csv("occurrences.csv", index=False)
print("Saved → occurrences.csv")

merged.to_csv("merged_all.csv", index=False)
print("Saved → merged_all.csv")

print("\nDone!")